name: create-apk

on: [pull_request]
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v3

      - name: ğŸ–¹ Check commit message
        id: commit_message_check
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: 'Release-As'
          flags: 'gm'
          error: 'The commit message does not contain "Release-As".'

      - name: ğŸ— Setup Node
        if: steps.commit_message_check.outputs.should_proceed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
          cache: npm

      - name: ğŸ— Setup EAS
        if: steps.commit_message_check.outputs.should_proceed == 'true'
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¦ Install dependencies
        if: steps.commit_message_check.outputs.should_proceed == 'true'
        run: npm install

      - name: ğŸš€ Create preview
        if: steps.commit_message_check.outputs.should_proceed == 'true'
        run: npm run eas:build